name: fsd-accelerating-waveforms
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13.1
  - astropy-base=7.1.0
  - matplotlib-base=3.10.5
  - numpy=2.3.2
  - pyyaml=6.0.2
  - scipy=1.16.0
  - ipykernel
  - nbclient
  - nbconvert=7.17.1
  - nbformat
  - pip
  - pycbc=2.9.0
  - pytest
  - setuptools=78.1.1
  - pip:
      - -e .
